services:
  check_transcripts_diploma:
    build: .
    container_name: check_transcripts_diploma
    working_dir: /app
    volumes:
      - .:/app
      - ./tests/res:/data:ro
      - ./streamlit/.streamlit/secrets.toml:/app/streamlit/.streamlit/secrets.toml:ro
    ports:
      - "8501:8501"
    restart: unless-stopped
